# .github/workflows/firebase-hosting-merge.yml

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci --legacy-peer-deps
      - name: Build Project
        run: npm run build
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEACHER_TOOLBOX_DB684 }}
          channelId: live
          projectId: teacher-toolbox-db684
        env:
          DEBUG: "true"
